### ISSUE TITLE
Can't select a port after setup ip_local_port_range

### ISSUE THREAD

**Issue by tomasz-sternumiot** [kmike/port-for#12]
Hi!

I encountered a bug (?) with `port-for-0.4` after changing the local port range in `/proc/sys/net/ipv4/ip_local_port_range`.

Please consider following test case:
```bash
# Installation of the python virtual environment and port-for package
~ $ python3.8 -mvenv port_for_test
./port_for_test/bin/pip install -U pip port-for
Collecting pip
  Using cached pip-21.0.1-py3-none-any.whl (1.5 MB)
Collecting port-for
  Using cached port_for-0.4-py2.py3-none-any.whl (21 kB)
Installing collected packages: pip, port-for
  Attempting uninstall: pip
    Found existing installation: pip 20.2.1
    Uninstalling pip-20.2.1:
      Successfully uninstalled pip-20.2.1
Successfully installed pip-21.0.1 port-for-0.4

# btw, here is another problem:
~ $ ./port_for_test/bin/port-for 
-bash: ./port_for_test/bin/port-for: /Users/kmike/envs/deep-deep/bin/python: bad interpreter: No such file or directory

# anyway, lets import it - the results are correct:
~ $ echo 'import port_for; print(port_for.select_random())' | ./port_for_test/bin/python
23623
~ $ echo 'import port_for; print(port_for.select_random())' | ./port_for_test/bin/python
28159
~ $ echo 'import port_for; print(port_for.select_random())' | ./port_for_test/bin/python
26734

# current ip_local_port_range is as follow:
~ $ cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999

# now, lets change (extend a little bit) the local port range
~ $ sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
net.ipv4.ip_local_port_range = 1024 65535

~ $ echo 'import port_for; print(port_for.select_random())' | ./port_for_test/bin/python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "port_for_test/lib/python3.8/site-packages/port_for/api.py", line 30, in select_random
    raise PortForException("Can't select a port")
port_for.exceptions.PortForException: Can't select a port
```

Please see here https://man7.org/linux/man-pages/man7/ip.7.html for a description of the `ip_local_port_range`.
I have tested binding to the ephemeral local port and it looks fine:
```bash
~ $ cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999

~ $ netcat -l 33000 &
[1] 2612325
~ $ echo "ok" | netcat 127.0.0.1 33000
ok
^C
```

Therefore, why there is a need to exclude ports from `ip_local_port_range`?

I'm using `Linux dev-env 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kmike** [comment]
> Therefore, why there is a need to exclude ports from ip_local_port_range?

The original motivation: let's say you decided to use an ephemeral local port as a persistent port, and "reserve" it to your software. OS won't know about it, and still can try to use this port. This is not a problem if your service is always running and occupying this port (OS would pick next one). But if the service is temporarily not using the port (because of restart of other reason), OS might reuse the same port, which might prevent the service from starting.

**Comment by fizyk** [comment]
@kmike I'll put that explanation as a comment in code

**Comment by kmike** [comment]
Thanks @fizyk! To add to it, this is not a theoretical concern, we were facing exactly this issue with our services, and this largely motivated creation of this package.
