### ISSUE TITLE
 Write access to /etc/port-for.conf!

### ISSUE THREAD

**Issue by capnping** [kmike/port-for#186]
I see there is no /etc/port-for.conf file present after python lib installation, is this file needed for python version or command line? Does python lib need to update any config file?

**Comment by fizyk** [comment]
@capnping no, then every installation would require you to use sudo.

**Comment by capnping** [comment]
> @capnping no, then every installation would require you to use sudo.

[/etc/port-for.conf](https://pypi.org/project/port-for/) refers to /etc/port-for.conf, which is not present after installation. is this document old, does this need update?
I tried port-for in windows, I am not able to get random port, does this module support in Windows?

**Comment by fizyk** [comment]
No, though I haven't touched the code regarding /etc/port-for.conf, it is there and expects it's existence by default. It's Dev responsibility to either create the file in this default location or create and point to config somewhere else. If installation would be too create three file, it would have to be required to install port-for with admin privileges.

And as for windows support, Windows is not POSIX compliant, but using WSL should work.

**Comment by capnping** [comment]
> No, though I haven't touched the code regarding /etc/port-for.conf, it is there and expects it's existence by default. It's Dev responsibility to either create the file in this default location or create and point to config somewhere else. If installation would be too create three file, it would have to be required to install port-for with admin privileges.
> 
> And as for windows support, Windows is not POSIX compliant, but using WSL should work.

Thanks
