### ISSUE TITLE
Add type hints / pep  561 

### ISSUE THREAD

**Issue by fizyk** [kmike/port-for#20]
Add type hints
Run mypy check on the port for
Make package compatible with [pep 561](https://www.python.org/dev/peps/pep-0561/)

**Comment by mmaslowskicc** [comment]
I think I can do this.

Do I correctly assume that we support only Python 3 (as in #8) and we should use the newer type annotation syntax here? There are some `__future__` imports suggesting compatibility with Python 2.5.

**Comment by fizyk** [comment]
Yes, you're correct. I'll remove most of the old references in due time. Focus on the versions tested on the CI
