### ISSUE TITLE
Python wheel uses bad python interpreter

### ISSUE THREAD

**Issue by agraubert** [kmike/port-for#3]
`port_for-0.4-py2.py3-none-any.whl`'s version of the port-for script seems to have `#!/Users/kmike/envs/deep-deep/bin/python` set as the interpreter to use.  I've verified this by manually unpacking the wheel and viewing the script.  Not a huge issue, as it's something that can be fixed by the end-user pretty quickly after installing, but I figured I'd mention it

**Comment by ava-dylang** [comment]
pip emits the same issue

**Comment by ava-dylang** [comment]
work around, prefer no binary `pip ... --no-binary=port-for port-for`
